name: Latest Release Build
run-name: Latest Release
on: [push]

jobs:
    Connect-to-docker:
        runs-on: ubuntu-latest
        steps:
            - run: echo "test"

    Build-New-APK:
        runs-on: ubuntu-latest
        steps:
            - run: echo "test2"
    
    update-latest-release:
        runs-on: ubuntu-latest
        steps:
            - run: echo "test3"
